import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import * as ImagePicker from "expo-image-picker";
import { router } from "expo-router";
import { useState } from "react";
import { StyleSheet, Text, TextInput, View } from "react-native";
import { AppButton } from "@/components/AppButton";
import { Card } from "@/components/Card";
import { PageHeader } from "@/components/PageHeader";
import { Screen } from "@/components/Screen";
import { colors, radius, spacing } from "@/constants/theme";
import { API_URL, type UploadAsset, reviewAndConfirm, uploadDocument } from "@/services/api";
import type { DocumentUpload, ExtractedLab } from "@/types/api";

export default function Upload() {
  const [result, setResult] = useState<DocumentUpload>(); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  async function send(asset: UploadAsset) { setBusy(true); setStatus("Uploading securely to the backend…"); try { const response = await uploadDocument(asset); setResult(response); setStatus(response.extraction.results.length ? "Extraction ready. Review every value." : "Uploaded. Add values manually if the image could not be parsed."); } catch (value) { setStatus(value instanceof Error ? value.message : "Upload failed."); } finally { setBusy(false); } }
  async function choosePdf() { const value = await DocumentPicker.getDocumentAsync({ type: "application/pdf", copyToCacheDirectory: true }); if (!value.canceled) await send({ uri: value.assets[0].uri, name: value.assets[0].name, mimeType: value.assets[0].mimeType || "application/pdf" }); }
  async function chooseImage(camera = false) { if (camera) { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) { setStatus("Camera permission is required to photograph a report."); return; } } const value = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ["images"], quality: .85 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: .9 }); if (!value.canceled) { const item = value.assets[0]; await send({ uri: item.uri, name: item.fileName || `lab-report.${item.mimeType === "image/png" ? "png" : "jpg"}`, mimeType: item.mimeType || "image/jpeg" }); } }
  async function demoLab() { if (!API_URL) return; setBusy(true); setStatus("Preparing the synthetic demo report…"); try { const uri = `${FileSystem.cacheDirectory}hasan-demo-lab-report.pdf`; const file = await FileSystem.downloadAsync(`${API_URL}/demo/assets/lab-report`, uri, { headers: { "X-Demo-User": "patient@demo.az" } }); await send({ uri: file.uri, name: "hasan-demo-lab-report.pdf", mimeType: "application/pdf" }); } catch (value) { setStatus(value instanceof Error ? value.message : "Demo report is unavailable."); setBusy(false); } }
  function update(index: number, key: keyof ExtractedLab, value: string) { setResult(current => current ? { ...current, extraction: { ...current.extraction, results: current.extraction.results.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: key === "value" ? Number(value) : value } : item) } } : current); }
  async function confirm() { if (!result) return; setBusy(true); setStatus("Saving reviewed values…"); try { const response = await reviewAndConfirm(result.document_id, result.extraction.results, result.extraction.report_date, result.extraction.source_name); setStatus(`Confirmed. ${response.results_created} new trusted values added; the timeline was updated.`); setTimeout(() => router.replace("/health/labs"), 900); } catch (value) { setStatus(value instanceof Error ? value.message : "Confirmation failed."); } finally { setBusy(false); } }
  return <Screen><PageHeader title="Upload Document" subtitle="Parsing happens only on the backend" back/><Card eyebrow="DEMO SHORTCUT" title="Synthetic lab report"><Text style={styles.muted}>Loads Hasan&apos;s safe 2026 sample PDF for the hackathon flow.</Text><AppButton label="Use Demo Lab Report" variant="secondary" loading={busy} onPress={demoLab}/></Card><Card title="Choose source"><View style={styles.actions}><AppButton label="Choose PDF" variant="secondary" disabled={busy} onPress={choosePdf}/><AppButton label="Choose Image" variant="secondary" disabled={busy} onPress={() => chooseImage(false)}/><AppButton label="Take Photo" variant="secondary" disabled={busy} onPress={() => chooseImage(true)}/></View></Card>{status ? <Text style={[styles.status, status.startsWith("Confirmed") && { color: colors.success }]}>{status}</Text> : null}{result ? <Card title="Review extracted values">{result.extraction.results.map((item, index) => <View key={`${item.test_name}-${index}`} style={styles.result}><TextInput accessibilityLabel="Test name" value={item.test_name} onChangeText={value => update(index, "test_name", value)} style={[styles.input, { flex: 1.4 }]}/><TextInput accessibilityLabel="Value" keyboardType="decimal-pad" value={String(item.value)} onChangeText={value => update(index, "value", value)} style={styles.input}/><TextInput accessibilityLabel="Unit" value={item.unit} onChangeText={value => update(index, "unit", value)} style={styles.input}/></View>)}<AppButton label="Add result" variant="secondary" onPress={() => setResult(current => current ? { ...current, extraction: { ...current.extraction, results: [...current.extraction.results, { test_name: "", value: 0, unit: "", reference_text: "" }] } } : current)}/><AppButton label="Confirm Reviewed Data" loading={busy} disabled={!result.extraction.results.length || result.extraction.results.some(x => !x.test_name)} onPress={confirm}/></Card> : null}<Text style={styles.disclaimer}>PDF, PNG, or JPG · maximum 15 MB · extracted values remain untrusted until you confirm them.</Text></Screen>;
}
const styles = StyleSheet.create({ muted: { color: colors.secondary, lineHeight: 20, marginBottom: spacing.md }, actions: { gap: spacing.sm }, status: { color: colors.primaryDark, backgroundColor: colors.primaryLight, borderRadius: radius.md, padding: spacing.md, lineHeight: 20, fontWeight: "700" }, result: { flexDirection: "row", gap: 6, marginBottom: spacing.sm }, input: { flex: 1, minHeight: 48, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.background, borderRadius: 12, paddingHorizontal: 10, color: colors.text }, disclaimer: { color: colors.secondary, fontSize: 11, lineHeight: 17, textAlign: "center" } });
