import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { AppButton } from "@/components/AppButton";
import { PageHeader } from "@/components/PageHeader";
import { Pill } from "@/components/Pill";
import { Screen } from "@/components/Screen";
import { EmptyState, ErrorState, LoadingState } from "@/components/States";
import { colors, radius, spacing } from "@/constants/theme";
import { useApi } from "@/hooks/useApi";
import { api, patch } from "@/services/api";
import type { Appointment, Queue } from "@/types/api";

type Segment = "Upcoming" | "Past" | "Cancelled";
export default function Appointments() {
  const [segment, setSegment] = useState<Segment>("Upcoming");
  const state = useApi(async () => { const appointments = await api<Appointment[]>("/appointments"); const queues: Record<string, Queue> = {}; await Promise.all(appointments.filter(x => !["COMPLETED", "CANCELLED"].includes(x.status)).map(async item => { try { queues[item.id] = await api<Queue>(`/appointments/${item.id}/queue`); } catch { /* status can change between polls */ } })); return { appointments, queues }; }, [], 5000);
  const items = useMemo(() => (state.data?.appointments ?? []).filter(item => segment === "Upcoming" ? !["COMPLETED", "CANCELLED"].includes(item.status) : segment === "Past" ? item.status === "COMPLETED" : item.status === "CANCELLED"), [state.data, segment]);
  async function cancel(id: string) { await patch(`/appointments/${id}/cancel`); await state.reload(); }
  if (state.loading && !state.data) return <Screen><LoadingState/></Screen>; if (!state.data) return <Screen><ErrorState message={state.error} retry={state.reload}/></Screen>;
  return <Screen refreshing={state.loading} onRefresh={state.reload}><PageHeader title="Appointments" subtitle="Queue refreshes every 5 seconds"/><View style={styles.segments}>{(["Upcoming", "Past", "Cancelled"] as Segment[]).map(item => <Pressable key={item} onPress={() => setSegment(item)} style={[styles.segment, segment === item && styles.active]}><Text style={[styles.segmentText, segment === item && styles.activeText]}>{item}</Text></Pressable>)}</View>{items.length ? items.map(item => { const queue = state.data!.queues[item.id]; return <Pressable key={item.id} onPress={() => router.push({ pathname: "/appointments/[id]", params: { id: item.id } })} style={styles.card}><View style={styles.top}><View style={{ flex: 1 }}><Text style={styles.name}>{item.doctor_name ?? "Dr. Leyla Mammadova"}</Text><Text style={styles.meta}>{item.specialty ?? "Endocrinology"}</Text></View><Pill label={item.status} tone={item.status === "WAITING" ? "amber" : "blue"}/></View><Text style={styles.time}>{new Date(item.starts_at).toLocaleString()}</Text>{queue ? <View style={styles.queue}><View><Text style={styles.queueLabel}>Queue position</Text><Text style={styles.queueValue}>{queue.queue_position}</Text></View><View><Text style={styles.queueLabel}>Estimated wait</Text><Text style={styles.queueValue}>{queue.estimated_wait_minutes} min</Text></View></View> : null}{segment === "Upcoming" ? <View style={styles.actions}><AppButton label="Reschedule" variant="secondary" onPress={() => router.push({ pathname: "/doctors/[id]", params: { id: item.doctor_id } })}/><AppButton label="Cancel" variant="danger" onPress={() => void cancel(item.id)}/></View> : null}</Pressable>; }) : <EmptyState title={`No ${segment.toLowerCase()} appointments`} message={segment === "Upcoming" ? "Find a doctor and choose an available time." : undefined}/>} {segment === "Upcoming" && !items.length ? <AppButton label="Find a Doctor" onPress={() => router.push("/(tabs)/doctors")}/> : null}</Screen>;
}
const styles = StyleSheet.create({ segments: { flexDirection: "row", backgroundColor: colors.muted, padding: 4, borderRadius: radius.md }, segment: { flex: 1, minHeight: 40, borderRadius: 12, alignItems: "center", justifyContent: "center" }, active: { backgroundColor: colors.card }, segmentText: { color: colors.secondary, fontWeight: "700", fontSize: 12 }, activeText: { color: colors.primaryDark }, card: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.lg }, top: { flexDirection: "row", gap: 10 }, name: { color: colors.text, fontSize: 17, fontWeight: "900" }, meta: { color: colors.primary, marginTop: 3, fontWeight: "700" }, time: { color: colors.secondary, marginTop: spacing.md }, queue: { flexDirection: "row", justifyContent: "space-around", backgroundColor: colors.primaryLight, borderRadius: 14, padding: spacing.md, marginTop: spacing.md }, queueLabel: { color: colors.secondary, fontSize: 11 }, queueValue: { color: colors.primaryDark, fontSize: 20, fontWeight: "900", marginTop: 3, textAlign: "center" }, actions: { flexDirection: "row", gap: spacing.sm, marginTop: spacing.md }, });
