import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { DoctorCard } from "@/components/DoctorCard";
import { PageHeader } from "@/components/PageHeader";
import { Screen } from "@/components/Screen";
import { EmptyState, ErrorState, LoadingState } from "@/components/States";
import { colors, radius, spacing } from "@/constants/theme";
import { useApi } from "@/hooks/useApi";
import { api } from "@/services/api";
import type { Doctor, Slot } from "@/types/api";

const filters = ["All", "Endocrinology", "Cardiology", "Neurology", "Dermatology", "Internal Medicine", "Surgery"];
export default function Doctors() {
  const [query, setQuery] = useState(""); const [specialty, setSpecialty] = useState("All"); const [covered, setCovered] = useState(false); const [available, setAvailable] = useState(false);
  const state = useApi(async () => { const doctors = await api<Doctor[]>("/doctors"); const slots = Object.fromEntries(await Promise.all(doctors.map(async doctor => [doctor.id, await api<Slot[]>(`/doctors/${doctor.id}/availability`)]))); return { doctors, slots: slots as Record<string, Slot[]> }; }, []);
  const items = useMemo(() => (state.data?.doctors ?? []).filter(doctor => { const text = `${doctor.name} ${doctor.specialty} ${doctor.hospital_name}`.toLowerCase(); const plans = Array.isArray(doctor.accepted_plans) ? doctor.accepted_plans : doctor.accepted_plans.split(","); const slots = state.data?.slots[doctor.id] ?? []; return (!query || text.includes(query.toLowerCase())) && (specialty === "All" || doctor.specialty === specialty) && (!covered || plans.includes("PLAN_PREMIUM")) && (!available || slots.some(x => x.status === "AVAILABLE")); }), [state.data, query, specialty, covered, available]);
  if (state.loading && !state.data) return <Screen><LoadingState label="Finding specialists…"/></Screen>; if (!state.data) return <Screen><ErrorState message={state.error} retry={state.reload}/></Screen>;
  return <Screen refreshing={state.loading} onRefresh={state.reload}><PageHeader title="Find a Doctor" subtitle={`${items.length} specialists match`}/><View style={styles.search}><MaterialCommunityIcons name="magnify" size={21} color={colors.secondary}/><TextInput value={query} onChangeText={setQuery} placeholder="Doctor, specialty, or hospital" placeholderTextColor={colors.secondary} style={styles.input}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map(item => <Pressable key={item} onPress={() => setSpecialty(item)} style={[styles.filter, specialty === item && styles.filterActive]}><Text style={[styles.filterText, specialty === item && styles.filterTextActive]}>{item}</Text></Pressable>)}</ScrollView><View style={styles.toggles}><Toggle label="Premium insurance" active={covered} onPress={() => setCovered(x => !x)}/><Toggle label="Available slots" active={available} onPress={() => setAvailable(x => !x)}/></View>{items.length ? items.map(doctor => <DoctorCard key={doctor.id} doctor={doctor} nextSlot={state.data!.slots[doctor.id]?.find(x => x.status === "AVAILABLE")} onPress={() => router.push({ pathname: "/doctors/[id]", params: { id: doctor.id } })}/>) : <EmptyState title="No doctors found" message="Try removing a filter."/>}</Screen>;
}
function Toggle({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.toggle, active && styles.toggleActive]}><MaterialCommunityIcons name={active ? "check-circle" : "circle-outline"} size={17} color={active ? colors.primary : colors.secondary}/><Text style={[styles.toggleText, active && { color: colors.primaryDark }]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ search: { height: 52, flexDirection: "row", alignItems: "center", gap: spacing.sm, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md }, input: { flex: 1, color: colors.text, fontSize: 15 }, filters: { gap: spacing.sm, paddingRight: spacing.lg }, filter: { borderRadius: 99, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, paddingVertical: 9 }, filterActive: { backgroundColor: colors.primary, borderColor: colors.primary }, filterText: { color: colors.secondary, fontWeight: "700", fontSize: 12 }, filterTextActive: { color: "white" }, toggles: { flexDirection: "row", gap: spacing.sm }, toggle: { flexDirection: "row", alignItems: "center", gap: 6, borderRadius: 99, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 10, paddingVertical: 8, backgroundColor: colors.card }, toggleActive: { backgroundColor: colors.primaryLight, borderColor: "#B7D1FA" }, toggleText: { color: colors.secondary, fontWeight: "700", fontSize: 12 } });
