import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Card } from "@/components/Card";
import { PageHeader } from "@/components/PageHeader";
import { Screen } from "@/components/Screen";
import { ErrorState, LoadingState } from "@/components/States";
import { colors, radius, spacing } from "@/constants/theme";
import { useApi } from "@/hooks/useApi";
import { api } from "@/services/api";
import type { Doctor, Slot } from "@/types/api";

export default function DoctorProfile() {
  const { id } = useLocalSearchParams<{ id: string }>(); const state = useApi(() => api<Doctor>(`/doctors/${id}`), [id]); const [day, setDay] = useState(0);
  const available = useMemo(() => (state.data?.availability ?? []).filter(x => x.status === "AVAILABLE"), [state.data]); const dates = [...new Set(available.map(x => x.starts_at.slice(0, 10)))]; const selectedDate = dates[day] ?? dates[0]; const daySlots = available.filter(x => x.starts_at.startsWith(selectedDate ?? ""));
  if (state.loading) return <Screen><LoadingState/></Screen>; if (!state.data) return <Screen><ErrorState message={state.error}/></Screen>; const doctor = state.data;
  return <Screen><PageHeader title="Doctor Profile" back/><View style={styles.hero}><View style={styles.avatar}><MaterialCommunityIcons name="doctor" size={46} color={colors.primary}/></View><Text style={styles.name}>{doctor.name}</Text><Text style={styles.specialty}>{doctor.specialty}</Text><Text style={styles.hospital}>{doctor.hospital_name} · {doctor.city}</Text><View style={styles.stats}><Stat label="Experience" value={`${doctor.experience_years} yrs`}/><Stat label="Rating" value={`★ ${doctor.rating}`}/><Stat label="Price" value={`${doctor.price} AZN`}/></View></View><Card title="Insurance"><Text style={styles.body}>{(doctor.accepted_plans as string[]).includes("PLAN_PREMIUM") ? "Premium Health accepted · 80% Endocrinology coverage" : "Check your plan before booking"}</Text></Card><Text style={styles.heading}>Select a date</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.days}>{dates.map((date, index) => <Pressable key={date} onPress={() => setDay(index)} style={[styles.day, day === index && styles.selected]}><Text style={[styles.dayName, day === index && styles.selectedText]}>{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: "short" })}</Text><Text style={[styles.dayDate, day === index && styles.selectedText]}>{new Date(`${date}T12:00:00`).getDate()}</Text></Pressable>)}</ScrollView><Text style={styles.heading}>Available times</Text><View style={styles.slots}>{daySlots.map(slot => <Pressable key={slot.id} onPress={() => router.push({ pathname: "/appointments/booking", params: { doctorId: doctor.id, slotId: slot.id } })} style={styles.slot}><Text style={styles.slotText}>{new Date(slot.starts_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</Text></Pressable>)}{!daySlots.length ? <Text style={styles.body}>No available times for this date.</Text> : null}</View></Screen>;
}
function Stat({ label, value }: { label: string; value: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ hero: { alignItems: "center", backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.xl }, avatar: { width: 88, height: 88, borderRadius: 28, backgroundColor: colors.primaryLight, alignItems: "center", justifyContent: "center" }, name: { color: colors.text, fontSize: 23, fontWeight: "900", marginTop: spacing.md }, specialty: { color: colors.primary, fontWeight: "800", marginTop: 4 }, hospital: { color: colors.secondary, marginTop: 5, textAlign: "center" }, stats: { flexDirection: "row", marginTop: spacing.xl, width: "100%" }, stat: { flex: 1, alignItems: "center", borderRightWidth: 1, borderRightColor: colors.border }, statValue: { color: colors.text, fontWeight: "900" }, statLabel: { color: colors.secondary, fontSize: 11, marginTop: 4 }, body: { color: colors.secondary, lineHeight: 20 }, heading: { color: colors.text, fontSize: 18, fontWeight: "900" }, days: { gap: spacing.sm }, day: { width: 64, paddingVertical: 12, borderRadius: 16, alignItems: "center", backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border }, selected: { backgroundColor: colors.primary, borderColor: colors.primary }, dayName: { color: colors.secondary, fontSize: 11, fontWeight: "700" }, dayDate: { color: colors.text, fontSize: 20, fontWeight: "900", marginTop: 3 }, selectedText: { color: "white" }, slots: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, slot: { minWidth: 78, paddingHorizontal: 15, paddingVertical: 13, borderRadius: 14, backgroundColor: colors.primaryLight, borderWidth: 1, borderColor: "#B7D1FA", alignItems: "center" }, slotText: { color: colors.primaryDark, fontWeight: "900" } });
