"use client";
import { useEffect, useState } from "react";
import { api, mutate, DemoRole } from "../lib/api";

type Trend={metric:string;current:number;previous:number|null;change:number;trend:string};
type Capacity={total_beds:number;occupied:number;available:number;emergency_waiting:number};
const roles: {label:string;value:DemoRole}[]=[{label:"Patient",value:"patient@demo.az"},{label:"Doctor",value:"doctor@demo.az"},{label:"Hospital Admin",value:"admin@demo.az"}];
export default function Home(){
 const [role,setRole]=useState<DemoRole>(roles[0].value),[data,setData]=useState<any>(),[error,setError]=useState("");
 useEffect(()=>{setData(undefined);setError(""); const load=async()=>{try{if(role===roles[0].value){const [trends,appointments,aiInsight]=await Promise.all([api<{trends:Trend[];care_navigation:{suggested_specialty:string;reason:string}}>("/patients/patient_hasan/trends",role),api<any[]>("/appointments",role),api<any>("/ai/lab-explanation/patient_hasan",role)]);setData({trends,appointments,aiInsight});}else if(role===roles[1].value){setData({appointments:await api<any[]>("/appointments",role)});}else{const [capacity,tasks,safety]=await Promise.all([api<Capacity>("/hospitals/hospital_caspian/capacity",role),api<any[]>("/tasks",role),api<any[]>("/safety/events",role)]);setData({capacity,tasks,safety});}}catch(e){setError("Backend unavailable. Start FastAPI on port 8000.")}};load()},[role]);
 return <main className="min-h-screen p-5 md:p-10"><div className="mx-auto max-w-5xl"><header className="mb-8 flex flex-col gap-4 rounded-[22px] border border-border bg-white p-6 shadow-sm md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-semibold text-primary">HEALTHTECH • DEMO MODE</p><h1 className="mt-1 text-3xl font-bold">Connected care, one system.</h1><p className="mt-2 text-gray-500">Live API-backed backbone preview</p></div><select aria-label="Demo role" className="rounded-2xl border border-border bg-white px-4 py-3 font-semibold" value={role} onChange={e=>setRole(e.target.value as DemoRole)}>{roles.map(r=><option key={r.value} value={r.value}>Demo as {r.label}</option>)}</select></header>{error&&<div className="rounded-2xl border-l-4 border-red-600 bg-white p-5 text-red-700">{error}</div>}{!data&&!error&&<p className="text-gray-500">Loading secure demo data…</p>}{data&& role===roles[0].value&&<PatientView data={data}/>} {data&& role===roles[1].value&&<DoctorView data={data}/>} {data&& role===roles[2].value&&<AdminView data={data}/>}</div></main>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><h2 className="font-bold">{title}</h2><div className="mt-4">{children}</div></section>}
function PatientView({data}:{data:any}){const hb=data.trends.trends.find((x:Trend)=>x.metric==="HbA1c");const insight=data.aiInsight?.ai?.content;return <div className="grid gap-5 md:grid-cols-2"><Card title="Good evening, Hasan"><p className="text-3xl font-bold text-green-600">Stable</p><p className="mt-2 text-sm text-gray-500">Your health record is up to date.</p></Card><Card title="Next appointment"><p className="font-semibold">{data.appointments[0]?.doctor_name ?? "No upcoming appointment"}</p><p className="text-sm text-gray-500">Book from the care navigation flow</p></Card><Card title="HbA1c trend"><p className="text-4xl font-bold">{hb?.current}% <span className="text-lg text-amber-600">↑ {hb?.change}</span></p><p className="mt-2 text-sm text-gray-500">Previous: {hb?.previous}% • {hb?.trend}</p></Card><section className="rounded-2xl border border-blue-200 bg-blue-50 p-5 shadow-sm"><p className="text-sm font-bold text-primary">✦ AI INSIGHT</p><p className="mt-3 font-semibold">{insight?.title ?? `${data.trends.care_navigation.suggested_specialty} review suggested`}</p><p className="mt-2 text-sm text-gray-600">{insight?.explanation ?? data.trends.care_navigation.reason}</p><button className="mt-4 rounded-2xl bg-primary px-5 py-3 font-semibold text-white">Find specialist</button></section></div>}
function DoctorView({data}:{data:any}){return <div className="grid gap-5 md:grid-cols-3"><Card title="Today's appointments"><p className="text-4xl font-bold">{data.appointments.length}</p></Card><Card title="AI alerts"><p className="text-4xl font-bold text-amber-600">4</p></Card><Card title="Follow-ups"><p className="text-4xl font-bold">2</p></Card><div className="md:col-span-3"><Card title="Today's patients"><ul className="space-y-3">{data.appointments.map((a:any)=><li key={a.id} className="flex justify-between border-b pb-3"><span className="font-semibold">{a.patient_name}</span><span className="text-gray-500">{new Date(a.starts_at).toLocaleString()}</span></li>)}</ul></Card></div></div>}
function AdminView({data}:{data:any}){const [events,setEvents]=useState<any[]>(data.safety??[]);const simulate=async()=>{await mutate("/cv-events","admin@demo.az",{room_id:"204",event_type:"FALL_RISK",severity:"HIGH",confidence:.91,patient_state:"STANDING",previous_state:"SITTING",metadata:{source:"dashboard_simulator"}});setEvents(await api<any[]>("/safety/events","admin@demo.az"));};return <div className="grid gap-5 md:grid-cols-4"><Card title="Total beds"><p className="text-3xl font-bold">{data.capacity.total_beds}</p></Card><Card title="Occupied"><p className="text-3xl font-bold">{data.capacity.occupied}</p></Card><Card title="Available"><p className="text-3xl font-bold text-green-600">{data.capacity.available}</p></Card><Card title="Emergency waiting"><p className="text-3xl font-bold text-red-600">{data.capacity.emergency_waiting}</p></Card><div className="md:col-span-2"><Card title="Priority discharge actions"><ul className="space-y-3">{data.tasks.map((t:any)=><li key={t.id} className="rounded-xl border-l-4 border-amber-500 bg-gray-50 p-4"><b>{t.title}</b> — {t.blocker_type}<br/><small>{t.impact}</small></li>)}</ul></Card></div><div className="md:col-span-2"><Card title="AI-assisted Patient Safety"><p className={events[0]?.status!=="RESOLVED"?"font-bold text-red-700":"font-bold text-green-700"}>Room 204: {events[0]?.status==="ACTIVE"?"HIGH FALL RISK":"Stable"}</p><p className="mt-2 text-sm text-gray-500">{events[0]?`State: ${events[0].previous_state} → ${events[0].patient_state} · ${Math.round(events[0].confidence*100)}% confidence`:"Prepared-video monitoring ready."}</p><button onClick={simulate} className="mt-4 rounded-2xl bg-primary px-5 py-3 font-semibold text-white">Simulate Fall Risk</button></Card></div></div>}
