import { useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { StyleSheet, Switch, Text, View } from "react-native";
import { AppButton } from "@/components/AppButton";
import { Card } from "@/components/Card";
import { PageHeader } from "@/components/PageHeader";
import { Pill } from "@/components/Pill";
import { Screen } from "@/components/Screen";
import { colors, radius, spacing } from "@/constants/theme";
import { useApi } from "@/hooks/useApi";
import { post } from "@/services/api";
import type { Consent } from "@/types/api";

const options = [{ key: "LAB_RESULTS", label: "Lab Results", initial: true }, { key: "MEDICATIONS", label: "Medications", initial: true }, { key: "DIAGNOSES", label: "Diagnoses / Metabolic History", initial: true }, { key: "DOCTOR_NOTES", label: "Doctor Notes", initial: true }, { key: "MENTAL_HEALTH", label: "Mental Health", initial: false }, { key: "DERMATOLOGY", label: "Dermatology", initial: false }];
const durations = [{ label: "1 hour", hours: 1 }, { label: "24 hours", hours: 24 }, { label: "7 days", hours: 168 }];
export default function Permissions() { const { doctorId = "doctor_leyla" } = useLocalSearchParams<{ doctorId?: string }>(); const [selected, setSelected] = useState(options.filter(x => x.initial).map(x => x.key)); const [hours, setHours] = useState(24); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const state = useApi(() => import("@/services/api").then(({ api }) => api<Consent[]>("/consents")), []); async function grant() { setSaving(true); setMessage(""); try { await post("/consents", { doctor_id: doctorId, categories: selected, hours }); setMessage(`Access granted for ${durations.find(x => x.hours === hours)?.label}.`); await state.reload(); } catch (value) { setMessage(value instanceof Error ? value.message : "Could not grant access."); } finally { setSaving(false); } } return <Screen><PageHeader title="Data Access" subtitle="You control what your doctor can view" back/><Card eyebrow="DOCTOR" title="Dr. Leyla Mammadova"><Text style={styles.muted}>Endocrinology · Access applies only to the selected categories.</Text></Card><Card title="Health information">{options.map(option => <View key={option.key} style={styles.option}><View style={{ flex: 1 }}><Text style={styles.optionLabel}>{option.label}</Text><Text style={styles.optionHint}>{option.initial ? "Recommended for this visit" : "Off by default"}</Text></View><Switch accessibilityLabel={option.label} value={selected.includes(option.key)} onValueChange={() => setSelected(value => value.includes(option.key) ? value.filter(x => x !== option.key) : [...value, option.key])} trackColor={{ false: colors.border, true: "#9FC1F5" }} thumbColor={selected.includes(option.key) ? colors.primary : "#F9FAFB"}/></View>)}</Card><Card title="Access duration"><View style={styles.durations}>{durations.map(item => <Text key={item.hours} onPress={() => setHours(item.hours)} style={[styles.duration, hours === item.hours && styles.durationActive]}>{item.label}</Text>)}</View></Card>{message ? <Text style={[styles.message, message.startsWith("Access granted") && { color: colors.success }]}>{message}</Text> : null}<AppButton label="Grant Access" loading={saving} disabled={!selected.length} onPress={grant}/>{state.data?.filter(x => x.status === "ACTIVE").map(item => <Card title={item.doctor_name} key={item.id}><Pill label="ACTIVE" tone="green"/><Text style={styles.muted}>Expires {new Date(item.expires_at).toLocaleString()}</Text></Card>)}</Screen>; }
const styles = StyleSheet.create({ muted: { color: colors.secondary, lineHeight: 20, marginTop: 6 }, option: { minHeight: 62, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: spacing.sm }, optionLabel: { color: colors.text, fontWeight: "800" }, optionHint: { color: colors.secondary, fontSize: 11, marginTop: 3 }, durations: { flexDirection: "row", gap: spacing.sm }, duration: { flex: 1, overflow: "hidden", textAlign: "center", color: colors.secondary, fontWeight: "800", borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingVertical: 13 }, durationActive: { color: "white", backgroundColor: colors.primary, borderColor: colors.primary }, message: { color: colors.danger, textAlign: "center", fontWeight: "700" } });
