import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { colors, radius, spacing } from "@/constants/theme";
import type { Doctor, Slot } from "@/types/api";
import { Pill } from "./Pill";

export function DoctorCard({ doctor, nextSlot, onPress }: { doctor: Doctor; nextSlot?: Slot; onPress: () => void }) {
  const plans = Array.isArray(doctor.accepted_plans) ? doctor.accepted_plans : doctor.accepted_plans.split(",");
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.card, pressed && { opacity: .72 }]}><View style={styles.top}><View style={styles.avatar}><MaterialCommunityIcons name="doctor" size={30} color={colors.primary}/></View><View style={styles.copy}><Text style={styles.name}>{doctor.name}</Text><Text style={styles.specialty}>{doctor.specialty}</Text><Text style={styles.hospital}>{doctor.hospital_name}</Text></View><View style={styles.rating}><MaterialCommunityIcons name="star" size={14} color={colors.warning}/><Text style={styles.ratingText}>{doctor.rating}</Text></View></View><View style={styles.divider}/><View style={styles.details}><View><Text style={styles.label}>Next available</Text><Text style={styles.detail}>{nextSlot ? new Date(nextSlot.starts_at).toLocaleString() : "Check profile"}</Text></View><View><Text style={styles.label}>Consultation</Text><Text style={styles.price}>{doctor.price} AZN</Text></View></View><View style={styles.footer}><Pill label={plans.includes("PLAN_PREMIUM") ? "Premium covered" : "Check coverage"} tone="green"/><Text style={styles.book}>View & Book →</Text></View></Pressable>;
}
const styles = StyleSheet.create({ card: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.lg }, top: { flexDirection: "row", gap: spacing.md }, avatar: { width: 54, height: 54, borderRadius: 18, backgroundColor: colors.primaryLight, alignItems: "center", justifyContent: "center" }, copy: { flex: 1 }, name: { color: colors.text, fontSize: 17, fontWeight: "900" }, specialty: { color: colors.primary, fontWeight: "700", marginTop: 3 }, hospital: { color: colors.secondary, fontSize: 12, marginTop: 3 }, rating: { flexDirection: "row", gap: 3 }, ratingText: { color: colors.text, fontWeight: "800", fontSize: 12 }, divider: { height: 1, backgroundColor: colors.border, marginVertical: spacing.md }, details: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, label: { color: colors.secondary, fontSize: 11 }, detail: { color: colors.text, fontWeight: "700", marginTop: 3, fontSize: 12, maxWidth: 210 }, price: { color: colors.text, fontWeight: "900", marginTop: 3 }, footer: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: spacing.md }, book: { color: colors.primary, fontWeight: "900", fontSize: 13 } });
