import { useLocalSearchParams } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { Card } from "@/components/Card";
import { PageHeader } from "@/components/PageHeader";
import { Pill } from "@/components/Pill";
import { Screen } from "@/components/Screen";
import { ErrorState, LoadingState } from "@/components/States";
import { colors, spacing } from "@/constants/theme";
import { useApi } from "@/hooks/useApi";
import { api } from "@/services/api";
import type { Appointment, Queue } from "@/types/api";

export default function AppointmentDetail() { const { id } = useLocalSearchParams<{ id: string }>(); const state = useApi(async () => { const appointment = (await api<Appointment[]>("/appointments")).find(x => x.id === id); if (!appointment) throw new Error("Appointment not found."); let queue: Queue | undefined; if (!["COMPLETED", "CANCELLED"].includes(appointment.status)) queue = await api<Queue>(`/appointments/${id}/queue`); return { appointment, queue }; }, [id], 5000); if (state.loading && !state.data) return <Screen><LoadingState/></Screen>; if (!state.data) return <Screen><ErrorState message={state.error} retry={state.reload}/></Screen>; const { appointment, queue } = state.data; return <Screen><PageHeader title="Appointment" subtitle="Live visit details" back/><Card><Pill label={appointment.status} tone={appointment.status === "WAITING" ? "amber" : "blue"}/><Text style={styles.name}>{appointment.doctor_name ?? "Dr. Leyla Mammadova"}</Text><Text style={styles.meta}>{appointment.specialty ?? "Endocrinology"} · {appointment.hospital_name ?? "Caspian Medical Center"}</Text><Text style={styles.time}>{new Date(appointment.starts_at).toLocaleString()}</Text></Card>{queue ? <Card title="Live queue"><View style={styles.queue}><Metric label="Position" value={String(queue.queue_position)}/><Metric label="Patients ahead" value={String(queue.patients_before)}/><Metric label="Wait" value={`${queue.estimated_wait_minutes} min`}/></View><Text style={styles.refresh}>Updates automatically every 5 seconds.</Text></Card> : null}<Card title="Reason"><Text style={styles.body}>{appointment.reason || "Endocrinology consultation"}</Text></Card></Screen>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ name: { color: colors.text, fontSize: 21, fontWeight: "900", marginTop: spacing.lg }, meta: { color: colors.primary, fontWeight: "700", marginTop: 4 }, time: { color: colors.secondary, marginTop: spacing.md }, queue: { flexDirection: "row" }, metric: { flex: 1, alignItems: "center" }, metricValue: { color: colors.primaryDark, fontSize: 22, fontWeight: "900" }, metricLabel: { color: colors.secondary, fontSize: 11, marginTop: 4, textAlign: "center" }, refresh: { color: colors.secondary, fontSize: 11, marginTop: spacing.md, textAlign: "center" }, body: { color: colors.secondary, lineHeight: 21 } });
