import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { AppButton } from "@/components/AppButton";
import { Card } from "@/components/Card";
import { PageHeader } from "@/components/PageHeader";
import { Screen } from "@/components/Screen";
import { ErrorState, LoadingState } from "@/components/States";
import { colors, spacing } from "@/constants/theme";
import { useApi } from "@/hooks/useApi";
import { PATIENT_ID, api, post } from "@/services/api";
import type { Doctor, InsuranceEstimate, Slot } from "@/types/api";

export default function Booking() {
  const { doctorId, slotId } = useLocalSearchParams<{ doctorId: string; slotId: string }>(); const [submitting, setSubmitting] = useState(false); const [confirmed, setConfirmed] = useState<{ id: string }>(); const [error, setError] = useState("");
  const state = useApi(async () => { const [doctor, estimate] = await Promise.all([api<Doctor>(`/doctors/${doctorId}`), api<InsuranceEstimate>(`/insurance/estimate?patient_id=${PATIENT_ID}&doctor_id=${doctorId}`)]); return { doctor, estimate, slot: doctor.availability?.find(x => x.id === slotId) }; }, [doctorId, slotId]);
  async function confirm() { setSubmitting(true); setError(""); try { setConfirmed(await post<{ id: string }>("/appointments", { doctor_id: doctorId, slot_id: slotId, reason: "Review increasing lab trend" })); } catch (value) { setError(value instanceof Error ? value.message : "Booking failed."); } finally { setSubmitting(false); } }
  if (state.loading) return <Screen><LoadingState/></Screen>; if (!state.data?.slot) return <Screen><ErrorState message={state.error || "This slot is unavailable."}/></Screen>; const { doctor, estimate, slot } = state.data;
  if (confirmed) return <Screen contentStyle={styles.successScreen}><View style={styles.successIcon}><MaterialCommunityIcons name="check" size={48} color="white"/></View><Text style={styles.successTitle}>Appointment Confirmed</Text><Text style={styles.successBody}>{doctor.name} · {new Date(slot.starts_at).toLocaleString()}</Text><AppButton label="Manage Data Access" onPress={() => router.replace({ pathname: "/permissions", params: { doctorId } })}/><AppButton label="View Appointments" variant="secondary" onPress={() => router.replace("/(tabs)/appointments")}/></Screen>;
  return <Screen><PageHeader title="Confirm Booking" subtitle="Doctor → Slot → Insurance → Confirm" back/><Card title="Appointment"><Text style={styles.name}>{doctor.name}</Text><Text style={styles.muted}>{doctor.specialty} · {doctor.hospital_name}</Text><Text style={styles.time}>{new Date(slot.starts_at).toLocaleString()}</Text></Card><Card title="Cost breakdown"><Cost label="Consultation" value={`${estimate.service_price} AZN`}/><Cost label={`Insurance (${estimate.coverage_percent}%)`} value={`−${estimate.insurance_payment} AZN`} green/><View style={styles.rule}/><Cost label="You pay" value={`${estimate.patient_payment} AZN`} large/></Card>{error ? <Text style={styles.error}>{error}</Text> : null}<AppButton label="Confirm Booking" loading={submitting} onPress={confirm}/><Text style={styles.disclaimer}>Your booking creates a real appointment in the demo backend. Medical access remains off until you grant consent.</Text></Screen>;
}
function Cost({ label, value, green, large }: { label: string; value: string; green?: boolean; large?: boolean }) { return <View style={styles.cost}><Text style={[styles.costLabel, large && styles.large]}>{label}</Text><Text style={[styles.costValue, green && { color: colors.success }, large && styles.large]}>{value}</Text></View>; }
const styles = StyleSheet.create({ name: { color: colors.text, fontSize: 20, fontWeight: "900" }, muted: { color: colors.secondary, marginTop: 5 }, time: { color: colors.primaryDark, fontWeight: "800", marginTop: spacing.md }, cost: { flexDirection: "row", justifyContent: "space-between", paddingVertical: spacing.sm }, costLabel: { color: colors.secondary }, costValue: { color: colors.text, fontWeight: "800" }, rule: { height: 1, backgroundColor: colors.border, marginVertical: spacing.sm }, large: { color: colors.text, fontSize: 19, fontWeight: "900" }, error: { color: colors.danger }, disclaimer: { color: colors.secondary, fontSize: 12, lineHeight: 18, textAlign: "center" }, successScreen: { flexGrow: 1, justifyContent: "center", alignItems: "stretch" }, successIcon: { alignSelf: "center", width: 92, height: 92, borderRadius: 46, backgroundColor: colors.success, alignItems: "center", justifyContent: "center" }, successTitle: { color: colors.text, fontSize: 27, fontWeight: "900", textAlign: "center" }, successBody: { color: colors.secondary, lineHeight: 21, textAlign: "center", marginBottom: spacing.lg } });
